//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Base;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.Base
{
    
    
    /// <summary>
    /// >> 215 - Composite[dot4gravity.Board]
    /// </summary>
    public sealed class Board : BaseType
    {
        
        /// <summary>
        /// >> cells
        /// </summary>
        private Ajuna.NetApi.Model.Base.Arr10Arr10EnumCell _cells;
        
        public Ajuna.NetApi.Model.Base.Arr10Arr10EnumCell Cells
        {
            get
            {
                return this._cells;
            }
            set
            {
                this._cells = value;
            }
        }
        
        public override string TypeName()
        {
            return "Board";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Cells.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Cells = new Ajuna.NetApi.Model.Base.Arr10Arr10EnumCell();
            Cells.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
