//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.Base
{
    
    
    public enum GamePhase
    {
        
        Bomb,
        
        Play,
    }
    
    /// <summary>
    /// >> 221 - Variant[dot4gravity.GamePhase]
    /// </summary>
    public sealed class EnumGamePhase : BaseEnum<GamePhase>
    {
    }
}
