//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.Base
{
    
    
    public enum Side
    {
        
        North,
        
        East,
        
        South,
        
        West,
    }
    
    /// <summary>
    /// >> 167 - Variant[dot4gravity.Side]
    /// </summary>
    public sealed class EnumSide : BaseEnum<Side>
    {
    }
}
