//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Base;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.Base
{
    
    
    /// <summary>
    /// >> 214 - Composite[dot4gravity.GameState]
    /// </summary>
    public sealed class GameState : BaseType
    {
        
        /// <summary>
        /// >> seed
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _seed;
        
        /// <summary>
        /// >> board
        /// </summary>
        private Ajuna.NetApi.Model.Base.Board _board;
        
        /// <summary>
        /// >> phase
        /// </summary>
        private Ajuna.NetApi.Model.Base.EnumGamePhase _phase;
        
        /// <summary>
        /// >> winner
        /// </summary>
        private BaseOpt<Ajuna.NetApi.Model.Types.Primitive.U8> _winner;
        
        /// <summary>
        /// >> next_player
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U8 _nextPlayer;
        
        /// <summary>
        /// >> players
        /// </summary>
        private Ajuna.NetApi.Model.Base.Arr2AccountId32 _players;
        
        /// <summary>
        /// >> bombs
        /// </summary>
        private Ajuna.NetApi.Model.Base.Arr2Special3 _bombs;
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 Seed
        {
            get
            {
                return this._seed;
            }
            set
            {
                this._seed = value;
            }
        }
        
        public Ajuna.NetApi.Model.Base.Board Board
        {
            get
            {
                return this._board;
            }
            set
            {
                this._board = value;
            }
        }
        
        public Ajuna.NetApi.Model.Base.EnumGamePhase Phase
        {
            get
            {
                return this._phase;
            }
            set
            {
                this._phase = value;
            }
        }
        
        public BaseOpt<Ajuna.NetApi.Model.Types.Primitive.U8> Winner
        {
            get
            {
                return this._winner;
            }
            set
            {
                this._winner = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U8 NextPlayer
        {
            get
            {
                return this._nextPlayer;
            }
            set
            {
                this._nextPlayer = value;
            }
        }
        
        public Ajuna.NetApi.Model.Base.Arr2AccountId32 Players
        {
            get
            {
                return this._players;
            }
            set
            {
                this._players = value;
            }
        }
        
        public Ajuna.NetApi.Model.Base.Arr2Special3 Bombs
        {
            get
            {
                return this._bombs;
            }
            set
            {
                this._bombs = value;
            }
        }
        
        public override string TypeName()
        {
            return "GameState";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Seed.Encode());
            result.AddRange(Board.Encode());
            result.AddRange(Phase.Encode());
            result.AddRange(Winner.Encode());
            result.AddRange(NextPlayer.Encode());
            result.AddRange(Players.Encode());
            result.AddRange(Bombs.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Seed = new Ajuna.NetApi.Model.Types.Primitive.U32();
            Seed.Decode(byteArray, ref p);
            Board = new Ajuna.NetApi.Model.Base.Board();
            Board.Decode(byteArray, ref p);
            Phase = new Ajuna.NetApi.Model.Base.EnumGamePhase();
            Phase.Decode(byteArray, ref p);
            Winner = new BaseOpt<Ajuna.NetApi.Model.Types.Primitive.U8>();
            Winner.Decode(byteArray, ref p);
            NextPlayer = new Ajuna.NetApi.Model.Types.Primitive.U8();
            NextPlayer.Decode(byteArray, ref p);
            Players = new Ajuna.NetApi.Model.Base.Arr2AccountId32();
            Players.Decode(byteArray, ref p);
            Bombs = new Ajuna.NetApi.Model.Base.Arr2Special3();
            Bombs.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
