//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.OrmlVesting;
using Ajuna.NetApi.Model.SpRuntime;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.OrmlVesting
{
    
    
    public enum Call
    {
        
        claim,
        
        vested_transfer,
        
        update_vesting_schedules,
        
        claim_for,
    }
    
    /// <summary>
    /// >> 145 - Variant[orml_vesting.module.Call]
    /// Contains one variant per dispatchable that can be called by an extrinsic.
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, BaseVoid, BaseTuple<Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress, Ajuna.NetApi.Model.OrmlVesting.VestingSchedule>, BaseTuple<Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress, BaseVec<Ajuna.NetApi.Model.OrmlVesting.VestingSchedule>>, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress>
    {
    }
}
