//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.AjunaSoloRuntime
{
    
    
    public enum NodeCall
    {
        
        System,
        
        Timestamp,
        
        Grandpa,
        
        Balances,
        
        Assets,
        
        Vesting,
        
        Council,
        
        CouncilMembership,
        
        Treasury,
        
        Democracy,
        
        Sudo,
        
        Scheduler,
        
        GameRegistry,
        
        Observers,
        
        Teerex,
    }
    
    /// <summary>
    /// >> 148 - Variant[ajuna_solo_runtime.Call]
    /// </summary>
    public sealed class EnumNodeCall : BaseEnum<NodeCall>
    {
    }
}
