//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletMatchmaker
{
    
    
    /// <summary>
    /// >> 56 - Composite[pallet_ajuna_matchmaker.Player]
    /// </summary>
    public sealed class Player : BaseType
    {
        
        /// <summary>
        /// >> account
        /// </summary>
        private Ajuna.NetApi.Model.SpCore.AccountId32 _account;
        
        public Ajuna.NetApi.Model.SpCore.AccountId32 Account
        {
            get
            {
                return this._account;
            }
            set
            {
                this._account = value;
            }
        }
        
        public override string TypeName()
        {
            return "Player";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Account.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Account = new Ajuna.NetApi.Model.SpCore.AccountId32();
            Account.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
