//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Meta;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi
{
    
    
    public sealed class SubstrateClientExt : Ajuna.NetApi.SubstrateClient
    {
        
        /// <summary>
        /// StorageKeyDict for key definition informations.
        /// </summary>
        public System.Collections.Generic.Dictionary<System.Tuple<string, string>, System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>> StorageKeyDict;
        
        /// <summary>
        /// SystemStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.FrameSystem.SystemStorage SystemStorage;
        
        /// <summary>
        /// TimestampStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletTimestamp.TimestampStorage TimestampStorage;
        
        /// <summary>
        /// AuraStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletAura.AuraStorage AuraStorage;
        
        /// <summary>
        /// GrandpaStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletGrandpa.GrandpaStorage GrandpaStorage;
        
        /// <summary>
        /// BalancesStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletBalances.BalancesStorage BalancesStorage;
        
        /// <summary>
        /// TransactionPaymentStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletTransactionPayment.TransactionPaymentStorage TransactionPaymentStorage;
        
        /// <summary>
        /// AssetTxPaymentStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletAssetTxPayment.AssetTxPaymentStorage AssetTxPaymentStorage;
        
        /// <summary>
        /// AssetsStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletAssets.AssetsStorage AssetsStorage;
        
        /// <summary>
        /// VestingStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletVesting.VestingStorage VestingStorage;
        
        /// <summary>
        /// CouncilStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletCouncil.CouncilStorage CouncilStorage;
        
        /// <summary>
        /// CouncilMembershipStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletCouncilMembership.CouncilMembershipStorage CouncilMembershipStorage;
        
        /// <summary>
        /// TreasuryStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletTreasury.TreasuryStorage TreasuryStorage;
        
        /// <summary>
        /// DemocracyStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletDemocracy.DemocracyStorage DemocracyStorage;
        
        /// <summary>
        /// SudoStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletSudo.SudoStorage SudoStorage;
        
        /// <summary>
        /// SchedulerStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletScheduler.SchedulerStorage SchedulerStorage;
        
        /// <summary>
        /// MatchmakerStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletMatchmaker.MatchmakerStorage MatchmakerStorage;
        
        /// <summary>
        /// RunnerStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletRunner.RunnerStorage RunnerStorage;
        
        /// <summary>
        /// GameRegistryStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletGameRegistry.GameRegistryStorage GameRegistryStorage;
        
        /// <summary>
        /// ObserversStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletObservers.ObserversStorage ObserversStorage;
        
        /// <summary>
        /// TeerexStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletTeerex.TeerexStorage TeerexStorage;
        
        /// <summary>
        /// SidechainStorage storage calls.
        /// </summary>
        public Ajuna.NetApi.Model.PalletSidechain.SidechainStorage SidechainStorage;
        
        public SubstrateClientExt(System.Uri uri) : 
                base(uri)
        {
            StorageKeyDict = new System.Collections.Generic.Dictionary<System.Tuple<string, string>, System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>>();
            this.SystemStorage = new Ajuna.NetApi.Model.FrameSystem.SystemStorage(this);
            this.TimestampStorage = new Ajuna.NetApi.Model.PalletTimestamp.TimestampStorage(this);
            this.AuraStorage = new Ajuna.NetApi.Model.PalletAura.AuraStorage(this);
            this.GrandpaStorage = new Ajuna.NetApi.Model.PalletGrandpa.GrandpaStorage(this);
            this.BalancesStorage = new Ajuna.NetApi.Model.PalletBalances.BalancesStorage(this);
            this.TransactionPaymentStorage = new Ajuna.NetApi.Model.PalletTransactionPayment.TransactionPaymentStorage(this);
            this.AssetTxPaymentStorage = new Ajuna.NetApi.Model.PalletAssetTxPayment.AssetTxPaymentStorage(this);
            this.AssetsStorage = new Ajuna.NetApi.Model.PalletAssets.AssetsStorage(this);
            this.VestingStorage = new Ajuna.NetApi.Model.PalletVesting.VestingStorage(this);
            this.CouncilStorage = new Ajuna.NetApi.Model.PalletCouncil.CouncilStorage(this);
            this.CouncilMembershipStorage = new Ajuna.NetApi.Model.PalletCouncilMembership.CouncilMembershipStorage(this);
            this.TreasuryStorage = new Ajuna.NetApi.Model.PalletTreasury.TreasuryStorage(this);
            this.DemocracyStorage = new Ajuna.NetApi.Model.PalletDemocracy.DemocracyStorage(this);
            this.SudoStorage = new Ajuna.NetApi.Model.PalletSudo.SudoStorage(this);
            this.SchedulerStorage = new Ajuna.NetApi.Model.PalletScheduler.SchedulerStorage(this);
            this.MatchmakerStorage = new Ajuna.NetApi.Model.PalletMatchmaker.MatchmakerStorage(this);
            this.RunnerStorage = new Ajuna.NetApi.Model.PalletRunner.RunnerStorage(this);
            this.GameRegistryStorage = new Ajuna.NetApi.Model.PalletGameRegistry.GameRegistryStorage(this);
            this.ObserversStorage = new Ajuna.NetApi.Model.PalletObservers.ObserversStorage(this);
            this.TeerexStorage = new Ajuna.NetApi.Model.PalletTeerex.TeerexStorage(this);
            this.SidechainStorage = new Ajuna.NetApi.Model.PalletSidechain.SidechainStorage(this);
        }
    }
}
