//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Base;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.SpRuntime
{
    
    
    public enum DigestItem
    {
        
        PreRuntime,
        
        Consensus,
        
        Seal,
        
        Other,
        
        RuntimeEnvironmentUpdated,
    }
    
    /// <summary>
    /// >> 13 - Variant[sp_runtime.generic.digest.DigestItem]
    /// </summary>
    public sealed class EnumDigestItem : BaseEnumExt<DigestItem, BaseTuple<Ajuna.NetApi.Model.Base.Arr4U8, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>>, BaseTuple<Ajuna.NetApi.Model.Base.Arr4U8, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>>, BaseTuple<Ajuna.NetApi.Model.Base.Arr4U8, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>>, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>, BaseVoid>
    {
    }
}
