//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.SpRuntime
{
    
    
    public enum TransactionalError
    {
        
        LimitReached,
        
        NoLayer,
    }
    
    /// <summary>
    /// >> 26 - Variant[sp_runtime.TransactionalError]
    /// </summary>
    public sealed class EnumTransactionalError : BaseEnum<TransactionalError>
    {
    }
}
