//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Base;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletBoard
{
    
    
    /// <summary>
    /// >> 210 - Composite[pallet_ajuna_board.guessing.GameState]
    /// </summary>
    public sealed class GameState : BaseType
    {
        
        /// <summary>
        /// >> players
        /// </summary>
        private Ajuna.NetApi.Model.Base.Arr2AccountId32 _players;
        
        /// <summary>
        /// >> next_player
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U8 _nextPlayer;
        
        /// <summary>
        /// >> solution
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _solution;
        
        /// <summary>
        /// >> winner
        /// </summary>
        private BaseOpt<Ajuna.NetApi.Model.SpCore.AccountId32> _winner;
        
        public Ajuna.NetApi.Model.Base.Arr2AccountId32 Players
        {
            get
            {
                return this._players;
            }
            set
            {
                this._players = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U8 NextPlayer
        {
            get
            {
                return this._nextPlayer;
            }
            set
            {
                this._nextPlayer = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 Solution
        {
            get
            {
                return this._solution;
            }
            set
            {
                this._solution = value;
            }
        }
        
        public BaseOpt<Ajuna.NetApi.Model.SpCore.AccountId32> Winner
        {
            get
            {
                return this._winner;
            }
            set
            {
                this._winner = value;
            }
        }
        
        public override string TypeName()
        {
            return "GameState";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Players.Encode());
            result.AddRange(NextPlayer.Encode());
            result.AddRange(Solution.Encode());
            result.AddRange(Winner.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Players = new Ajuna.NetApi.Model.Base.Arr2AccountId32();
            Players.Decode(byteArray, ref p);
            NextPlayer = new Ajuna.NetApi.Model.Types.Primitive.U8();
            NextPlayer.Decode(byteArray, ref p);
            Solution = new Ajuna.NetApi.Model.Types.Primitive.U32();
            Solution.Decode(byteArray, ref p);
            Winner = new BaseOpt<Ajuna.NetApi.Model.SpCore.AccountId32>();
            Winner.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
