//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.IasVerify
{
    
    
    public enum SgxBuildMode
    {
        
        Debug,
        
        Production,
    }
    
    /// <summary>
    /// >> 212 - Variant[ias_verify.SgxBuildMode]
    /// </summary>
    public sealed class EnumSgxBuildMode : BaseEnum<SgxBuildMode>
    {
    }
}
