//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.AjunaRuntime;
using Ajuna.NetApi.Model.PrimitiveTypes;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.FrameSupport
{
    
    
    public enum MaybeHashed
    {
        
        Value,
        
        Hash,
    }
    
    /// <summary>
    /// >> 139 - Variant[frame_support.traits.schedule.MaybeHashed]
    /// </summary>
    public sealed class EnumMaybeHashed : BaseEnumExt<MaybeHashed, Ajuna.NetApi.Model.AjunaRuntime.EnumNodeCall, Ajuna.NetApi.Model.PrimitiveTypes.H256>
    {
    }
}
