//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.SpArithmetic;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.FrameSupport
{
    
    
    /// <summary>
    /// >> 131 - Composite[frame_support.weights.WeightToFeeCoefficient]
    /// </summary>
    public sealed class WeightToFeeCoefficient : BaseType
    {
        
        /// <summary>
        /// >> coeff_integer
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U128 _coeffInteger;
        
        /// <summary>
        /// >> coeff_frac
        /// </summary>
        private Ajuna.NetApi.Model.SpArithmetic.Perbill _coeffFrac;
        
        /// <summary>
        /// >> negative
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.Bool _negative;
        
        /// <summary>
        /// >> degree
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U8 _degree;
        
        public Ajuna.NetApi.Model.Types.Primitive.U128 CoeffInteger
        {
            get
            {
                return this._coeffInteger;
            }
            set
            {
                this._coeffInteger = value;
            }
        }
        
        public Ajuna.NetApi.Model.SpArithmetic.Perbill CoeffFrac
        {
            get
            {
                return this._coeffFrac;
            }
            set
            {
                this._coeffFrac = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.Bool Negative
        {
            get
            {
                return this._negative;
            }
            set
            {
                this._negative = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U8 Degree
        {
            get
            {
                return this._degree;
            }
            set
            {
                this._degree = value;
            }
        }
        
        public override string TypeName()
        {
            return "WeightToFeeCoefficient";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(CoeffInteger.Encode());
            result.AddRange(CoeffFrac.Encode());
            result.AddRange(Negative.Encode());
            result.AddRange(Degree.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            CoeffInteger = new Ajuna.NetApi.Model.Types.Primitive.U128();
            CoeffInteger.Decode(byteArray, ref p);
            CoeffFrac = new Ajuna.NetApi.Model.SpArithmetic.Perbill();
            CoeffFrac.Decode(byteArray, ref p);
            Negative = new Ajuna.NetApi.Model.Types.Primitive.Bool();
            Negative.Decode(byteArray, ref p);
            Degree = new Ajuna.NetApi.Model.Types.Primitive.U8();
            Degree.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
