//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletDemocracy
{
    
    
    public enum Conviction
    {
        
        None,
        
        Locked1x,
        
        Locked2x,
        
        Locked3x,
        
        Locked4x,
        
        Locked5x,
        
        Locked6x,
    }
    
    /// <summary>
    /// >> 153 - Variant[pallet_democracy.conviction.Conviction]
    /// </summary>
    public sealed class EnumConviction : BaseEnum<Conviction>
    {
    }
}
