//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.PalletDemocracy;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletDemocracy
{
    
    
    public enum Voting
    {
        
        Direct,
        
        Delegating,
    }
    
    /// <summary>
    /// >> 179 - Variant[pallet_democracy.vote.Voting]
    /// </summary>
    public sealed class EnumVoting : BaseEnumExt<Voting, BaseTuple<BaseVec<BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.PalletDemocracy.EnumAccountVote>>, Ajuna.NetApi.Model.PalletDemocracy.Delegations, Ajuna.NetApi.Model.PalletDemocracy.PriorLock>, BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U128, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.PalletDemocracy.EnumConviction, Ajuna.NetApi.Model.PalletDemocracy.Delegations, Ajuna.NetApi.Model.PalletDemocracy.PriorLock>>
    {
    }
}
