//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.FinalityGrandpa;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.SpFinalityGrandpa
{
    
    
    public enum Equivocation
    {
        
        Prevote,
        
        Precommit,
    }
    
    /// <summary>
    /// >> 103 - Variant[sp_finality_grandpa.Equivocation]
    /// </summary>
    public sealed class EnumEquivocation : BaseEnumExt<Equivocation, Ajuna.NetApi.Model.FinalityGrandpa.EquivocationT1, Ajuna.NetApi.Model.FinalityGrandpa.EquivocationT2>
    {
    }
}
