//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Extrinsics;
using Ajuna.NetApi.Model.Meta;
using Ajuna.NetApi.Model.PrimitiveTypes;
using Ajuna.NetApi.Model.SidechainPrimitives;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace Ajuna.NetApi.Model.PalletSidechain
{
    
    
    public sealed class SidechainStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateClientExt _client;
        
        public SidechainStorage(SubstrateClientExt client)
        {
            this._client = client;
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Sidechain", "WorkerForShard"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(Ajuna.NetApi.Model.PrimitiveTypes.H256), typeof(Ajuna.NetApi.Model.Types.Primitive.U64)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Sidechain", "LatestSidechainHeader"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(Ajuna.NetApi.Model.PrimitiveTypes.H256), typeof(Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Sidechain", "SidechainHeaderQueue"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(BaseTuple<BaseTuple<Ajuna.NetApi.Model.PrimitiveTypes.H256,Ajuna.NetApi.Model.Types.Primitive.U64>,Ajuna.NetApi.Model.PrimitiveTypes.H256>), typeof(Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader)));
        }
        
        /// <summary>
        /// >> WorkerForShardParams
        /// </summary>
        public static string WorkerForShardParams(Ajuna.NetApi.Model.PrimitiveTypes.H256 key)
        {
            return RequestGenerator.GetStorage("Sidechain", "WorkerForShard", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> WorkerForShard
        /// </summary>
        public async Task<Ajuna.NetApi.Model.Types.Primitive.U64> WorkerForShard(Ajuna.NetApi.Model.PrimitiveTypes.H256 key, CancellationToken token)
        {
            string parameters = SidechainStorage.WorkerForShardParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.Types.Primitive.U64>(parameters, token);
        }
        
        /// <summary>
        /// >> LatestSidechainHeaderParams
        /// </summary>
        public static string LatestSidechainHeaderParams(Ajuna.NetApi.Model.PrimitiveTypes.H256 key)
        {
            return RequestGenerator.GetStorage("Sidechain", "LatestSidechainHeader", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> LatestSidechainHeader
        /// </summary>
        public async Task<Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader> LatestSidechainHeader(Ajuna.NetApi.Model.PrimitiveTypes.H256 key, CancellationToken token)
        {
            string parameters = SidechainStorage.LatestSidechainHeaderParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader>(parameters, token);
        }
        
        /// <summary>
        /// >> SidechainHeaderQueueParams
        /// </summary>
        public static string SidechainHeaderQueueParams(BaseTuple<BaseTuple<Ajuna.NetApi.Model.PrimitiveTypes.H256,Ajuna.NetApi.Model.Types.Primitive.U64>,Ajuna.NetApi.Model.PrimitiveTypes.H256> key)
        {
            return RequestGenerator.GetStorage("Sidechain", "SidechainHeaderQueue", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> SidechainHeaderQueue
        /// </summary>
        public async Task<Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader> SidechainHeaderQueue(BaseTuple<BaseTuple<Ajuna.NetApi.Model.PrimitiveTypes.H256,Ajuna.NetApi.Model.Types.Primitive.U64>,Ajuna.NetApi.Model.PrimitiveTypes.H256> key, CancellationToken token)
        {
            string parameters = SidechainStorage.SidechainHeaderQueueParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader>(parameters, token);
        }
    }
    
    public sealed class SidechainCalls
    {
        
        /// <summary>
        /// >> confirm_proposed_sidechain_block
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ConfirmProposedSidechainBlock(Ajuna.NetApi.Model.PrimitiveTypes.H256 shard_id, Ajuna.NetApi.Model.SidechainPrimitives.SidechainHeader header)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(shard_id.Encode());
            byteArray.AddRange(header.Encode());
            return new Method(20, "Sidechain", 0, "confirm_proposed_sidechain_block", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> ProposedSidechainBlock
    /// </summary>
    public sealed class EventProposedSidechainBlock : BaseTuple<Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.PrimitiveTypes.H256>
    {
    }
    
    public enum SidechainErrors
    {
        
        /// <summary>
        /// >> BlockNumberTooHigh
        /// A proposed block is too early.
        /// </summary>
        BlockNumberTooHigh,
        
        /// <summary>
        /// >> OutdatedBlockNumber
        /// A propsed block is too late and already outdated.
        /// </summary>
        OutdatedBlockNumber,
    }
}
