//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.FrameSupport
{
    
    
    public enum BalanceStatus
    {
        
        Free,
        
        Reserved,
    }
    
    /// <summary>
    /// >> 33 - Variant[frame_support.traits.tokens.misc.BalanceStatus]
    /// </summary>
    public sealed class EnumBalanceStatus : BaseEnum<BalanceStatus>
    {
    }
}
