//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.AjunaCommon;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.AjunaCommon
{
    
    
    public enum RunnerState
    {
        
        Queued,
        
        Accepted,
        
        Finished,
    }
    
    /// <summary>
    /// >> 195 - Variant[ajuna_common.RunnerState]
    /// </summary>
    public sealed class EnumRunnerState : BaseEnumExt<RunnerState, Ajuna.NetApi.Model.AjunaCommon.State, Ajuna.NetApi.Model.AjunaCommon.State, Ajuna.NetApi.Model.AjunaCommon.State>
    {
    }
}
