//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.FrameSystem
{
    
    
    public enum RawOrigin
    {
        
        Root,
        
        Signed,
        
        None,
    }
    
    /// <summary>
    /// >> 156 - Variant[frame_system.RawOrigin]
    /// </summary>
    public sealed class EnumRawOrigin : BaseEnumExt<RawOrigin, BaseVoid, Ajuna.NetApi.Model.SpCore.AccountId32, BaseVoid>
    {
    }
}
