//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.AjunaRuntime;
using Ajuna.NetApi.Model.FrameSystem;
using Ajuna.NetApi.Model.PrimitiveTypes;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.FrameSystem
{
    
    
    /// <summary>
    /// >> 16 - Composite[frame_system.EventRecord]
    /// </summary>
    public sealed class EventRecord : BaseType
    {
        
        /// <summary>
        /// >> phase
        /// </summary>
        private Ajuna.NetApi.Model.FrameSystem.EnumPhase _phase;
        
        /// <summary>
        /// >> event
        /// </summary>
        private Ajuna.NetApi.Model.AjunaRuntime.EnumNodeEvent _event;
        
        /// <summary>
        /// >> topics
        /// </summary>
        private BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256> _topics;
        
        public Ajuna.NetApi.Model.FrameSystem.EnumPhase Phase
        {
            get
            {
                return this._phase;
            }
            set
            {
                this._phase = value;
            }
        }
        
        public Ajuna.NetApi.Model.AjunaRuntime.EnumNodeEvent Event
        {
            get
            {
                return this._event;
            }
            set
            {
                this._event = value;
            }
        }
        
        public BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256> Topics
        {
            get
            {
                return this._topics;
            }
            set
            {
                this._topics = value;
            }
        }
        
        public override string TypeName()
        {
            return "EventRecord";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Phase.Encode());
            result.AddRange(Event.Encode());
            result.AddRange(Topics.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Phase = new Ajuna.NetApi.Model.FrameSystem.EnumPhase();
            Phase.Decode(byteArray, ref p);
            Event = new Ajuna.NetApi.Model.AjunaRuntime.EnumNodeEvent();
            Event.Decode(byteArray, ref p);
            Topics = new BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256>();
            Topics.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
