//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletBalances
{
    
    
    public enum Reasons
    {
        
        Fee,
        
        Misc,
        
        All,
    }
    
    /// <summary>
    /// >> 105 - Variant[pallet_balances.Reasons]
    /// </summary>
    public sealed class EnumReasons : BaseEnum<Reasons>
    {
    }
}
