//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletGameregistry
{
    
    
    public enum RequirementType
    {
        
        PlayersPerGame,
    }
    
    /// <summary>
    /// >> 204 - Variant[pallet_ajuna_gameregistry.game.requirement.RequirementType]
    /// </summary>
    public sealed class EnumRequirementType : BaseEnumExt<RequirementType, Ajuna.NetApi.Model.Types.Primitive.U32>
    {
    }
}
