//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletGameregistry
{
    
    
    /// <summary>
    /// >> 49 - Composite[pallet_ajuna_gameregistry.game.GameEngine]
    /// </summary>
    public sealed class GameEngine : BaseType
    {
        
        /// <summary>
        /// >> id
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U8 _id;
        
        /// <summary>
        /// >> version
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U8 _version;
        
        public Ajuna.NetApi.Model.Types.Primitive.U8 Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U8 Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
        
        public override string TypeName()
        {
            return "GameEngine";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Id.Encode());
            result.AddRange(Version.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Id = new Ajuna.NetApi.Model.Types.Primitive.U8();
            Id.Decode(byteArray, ref p);
            Version = new Ajuna.NetApi.Model.Types.Primitive.U8();
            Version.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
