//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.PrimitiveTypes;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletGameregistry
{
    
    
    /// <summary>
    /// >> 162 - Composite[pallet_ajuna_gameregistry.queue.Queue]
    /// </summary>
    public sealed class Queue : BaseType
    {
        
        /// <summary>
        /// >> max_size
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _maxSize;
        
        /// <summary>
        /// >> queue
        /// </summary>
        private BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256> _queue;
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 MaxSize
        {
            get
            {
                return this._maxSize;
            }
            set
            {
                this._maxSize = value;
            }
        }
        
        public BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256> GameQueue
        {
            get
            {
                return this._queue;
            }
            set
            {
                this._queue = value;
            }
        }
        
        public override string TypeName()
        {
            return "Queue";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(MaxSize.Encode());
            result.AddRange(GameQueue.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            MaxSize = new Ajuna.NetApi.Model.Types.Primitive.U32();
            MaxSize.Decode(byteArray, ref p);
            GameQueue = new BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256>();
            GameQueue.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
