//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Base;
using Ajuna.NetApi.Model.PalletGameregistry;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletGameregistry
{
    
    
    /// <summary>
    /// >> 203 - Composite[pallet_ajuna_gameregistry.game.requirement.Requirement]
    /// </summary>
    public sealed class Requirement : BaseType
    {
        
        /// <summary>
        /// >> kind
        /// </summary>
        private Ajuna.NetApi.Model.PalletGameregistry.EnumRequirementType _kind;
        
        /// <summary>
        /// >> requirement_info
        /// </summary>
        private Ajuna.NetApi.Model.Base.Arr16U8 _requirementInfo;
        
        public Ajuna.NetApi.Model.PalletGameregistry.EnumRequirementType Kind
        {
            get
            {
                return this._kind;
            }
            set
            {
                this._kind = value;
            }
        }
        
        public Ajuna.NetApi.Model.Base.Arr16U8 RequirementInfo
        {
            get
            {
                return this._requirementInfo;
            }
            set
            {
                this._requirementInfo = value;
            }
        }
        
        public override string TypeName()
        {
            return "Requirement";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Kind.Encode());
            result.AddRange(RequirementInfo.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Kind = new Ajuna.NetApi.Model.PalletGameregistry.EnumRequirementType();
            Kind.Decode(byteArray, ref p);
            RequirementInfo = new Ajuna.NetApi.Model.Base.Arr16U8();
            RequirementInfo.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
