//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Extrinsics;
using Ajuna.NetApi.Model.Meta;
using Ajuna.NetApi.Model.PalletAssets;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.SpRuntime;
using Ajuna.NetApi.Model.Types;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace Ajuna.NetApi.Model.PalletAssets
{
    
    
    public sealed class AssetsStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateClientExt _client;
        
        public AssetsStorage(SubstrateClientExt client)
        {
            this._client = client;
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Assets", "Asset"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(Ajuna.NetApi.Model.Types.Primitive.U32), typeof(Ajuna.NetApi.Model.PalletAssets.AssetDetails)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Assets", "Account"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.SpCore.AccountId32>), typeof(Ajuna.NetApi.Model.PalletAssets.AssetAccount)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Assets", "Approvals"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.SpCore.AccountId32,Ajuna.NetApi.Model.SpCore.AccountId32>), typeof(Ajuna.NetApi.Model.PalletAssets.Approval)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("Assets", "Metadata"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(Ajuna.NetApi.Model.Types.Primitive.U32), typeof(Ajuna.NetApi.Model.PalletAssets.AssetMetadata)));
        }
        
        /// <summary>
        /// >> AssetParams
        ///  Details of an asset.
        /// </summary>
        public static string AssetParams(Ajuna.NetApi.Model.Types.Primitive.U32 key)
        {
            return RequestGenerator.GetStorage("Assets", "Asset", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> Asset
        ///  Details of an asset.
        /// </summary>
        public async Task<Ajuna.NetApi.Model.PalletAssets.AssetDetails> Asset(Ajuna.NetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = AssetsStorage.AssetParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.PalletAssets.AssetDetails>(parameters, token);
        }
        
        /// <summary>
        /// >> AccountParams
        ///  The holdings of a specific account for a specific asset.
        /// </summary>
        public static string AccountParams(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.SpCore.AccountId32> key)
        {
            return RequestGenerator.GetStorage("Assets", "Account", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> Account
        ///  The holdings of a specific account for a specific asset.
        /// </summary>
        public async Task<Ajuna.NetApi.Model.PalletAssets.AssetAccount> Account(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = AssetsStorage.AccountParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.PalletAssets.AssetAccount>(parameters, token);
        }
        
        /// <summary>
        /// >> ApprovalsParams
        ///  Approved balance transfers. First balance is the amount approved for transfer. Second
        ///  is the amount of `T::Currency` reserved for storing this.
        ///  First key is the asset ID, second key is the owner and third key is the delegate.
        /// </summary>
        public static string ApprovalsParams(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.SpCore.AccountId32,Ajuna.NetApi.Model.SpCore.AccountId32> key)
        {
            return RequestGenerator.GetStorage("Assets", "Approvals", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> Approvals
        ///  Approved balance transfers. First balance is the amount approved for transfer. Second
        ///  is the amount of `T::Currency` reserved for storing this.
        ///  First key is the asset ID, second key is the owner and third key is the delegate.
        /// </summary>
        public async Task<Ajuna.NetApi.Model.PalletAssets.Approval> Approvals(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32,Ajuna.NetApi.Model.SpCore.AccountId32,Ajuna.NetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = AssetsStorage.ApprovalsParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.PalletAssets.Approval>(parameters, token);
        }
        
        /// <summary>
        /// >> MetadataParams
        ///  Metadata of an asset.
        /// </summary>
        public static string MetadataParams(Ajuna.NetApi.Model.Types.Primitive.U32 key)
        {
            return RequestGenerator.GetStorage("Assets", "Metadata", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> Metadata
        ///  Metadata of an asset.
        /// </summary>
        public async Task<Ajuna.NetApi.Model.PalletAssets.AssetMetadata> Metadata(Ajuna.NetApi.Model.Types.Primitive.U32 key, CancellationToken token)
        {
            string parameters = AssetsStorage.MetadataParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.PalletAssets.AssetMetadata>(parameters, token);
        }
    }
    
    public sealed class AssetsCalls
    {
        
        /// <summary>
        /// >> create
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Create(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress admin, Ajuna.NetApi.Model.Types.Primitive.U128 min_balance)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(admin.Encode());
            byteArray.AddRange(min_balance.Encode());
            return new Method(7, "Assets", 0, "create", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_create
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ForceCreate(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress owner, Ajuna.NetApi.Model.Types.Primitive.Bool is_sufficient, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> min_balance)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(owner.Encode());
            byteArray.AddRange(is_sufficient.Encode());
            byteArray.AddRange(min_balance.Encode());
            return new Method(7, "Assets", 1, "force_create", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> destroy
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Destroy(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.PalletAssets.DestroyWitness witness)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(witness.Encode());
            return new Method(7, "Assets", 2, "destroy", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> mint
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Mint(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress beneficiary, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(beneficiary.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 3, "mint", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> burn
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Burn(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress who, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(who.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 4, "burn", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> transfer
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Transfer(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress target, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(target.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 5, "transfer", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> transfer_keep_alive
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method TransferKeepAlive(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress target, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(target.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 6, "transfer_keep_alive", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_transfer
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ForceTransfer(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress source, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress dest, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(source.Encode());
            byteArray.AddRange(dest.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 7, "force_transfer", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> freeze
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Freeze(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress who)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(who.Encode());
            return new Method(7, "Assets", 8, "freeze", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> thaw
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Thaw(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress who)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(who.Encode());
            return new Method(7, "Assets", 9, "thaw", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> freeze_asset
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method FreezeAsset(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            return new Method(7, "Assets", 10, "freeze_asset", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> thaw_asset
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ThawAsset(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            return new Method(7, "Assets", 11, "thaw_asset", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> transfer_ownership
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method TransferOwnership(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress owner)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(owner.Encode());
            return new Method(7, "Assets", 12, "transfer_ownership", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_team
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method SetTeam(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress issuer, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress admin, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress freezer)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(issuer.Encode());
            byteArray.AddRange(admin.Encode());
            byteArray.AddRange(freezer.Encode());
            return new Method(7, "Assets", 13, "set_team", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> set_metadata
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method SetMetadata(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> name, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> symbol, Ajuna.NetApi.Model.Types.Primitive.U8 decimals)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(name.Encode());
            byteArray.AddRange(symbol.Encode());
            byteArray.AddRange(decimals.Encode());
            return new Method(7, "Assets", 14, "set_metadata", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> clear_metadata
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ClearMetadata(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            return new Method(7, "Assets", 15, "clear_metadata", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_set_metadata
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ForceSetMetadata(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> name, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> symbol, Ajuna.NetApi.Model.Types.Primitive.U8 decimals, Ajuna.NetApi.Model.Types.Primitive.Bool is_frozen)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(name.Encode());
            byteArray.AddRange(symbol.Encode());
            byteArray.AddRange(decimals.Encode());
            byteArray.AddRange(is_frozen.Encode());
            return new Method(7, "Assets", 16, "force_set_metadata", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_clear_metadata
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ForceClearMetadata(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            return new Method(7, "Assets", 17, "force_clear_metadata", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_asset_status
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ForceAssetStatus(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress owner, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress issuer, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress admin, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress freezer, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> min_balance, Ajuna.NetApi.Model.Types.Primitive.Bool is_sufficient, Ajuna.NetApi.Model.Types.Primitive.Bool is_frozen)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(owner.Encode());
            byteArray.AddRange(issuer.Encode());
            byteArray.AddRange(admin.Encode());
            byteArray.AddRange(freezer.Encode());
            byteArray.AddRange(min_balance.Encode());
            byteArray.AddRange(is_sufficient.Encode());
            byteArray.AddRange(is_frozen.Encode());
            return new Method(7, "Assets", 18, "force_asset_status", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> approve_transfer
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ApproveTransfer(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress @delegate, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(@delegate.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 19, "approve_transfer", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> cancel_approval
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method CancelApproval(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress @delegate)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(@delegate.Encode());
            return new Method(7, "Assets", 20, "cancel_approval", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> force_cancel_approval
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method ForceCancelApproval(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress owner, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress @delegate)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(owner.Encode());
            byteArray.AddRange(@delegate.Encode());
            return new Method(7, "Assets", 21, "force_cancel_approval", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> transfer_approved
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method TransferApproved(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress owner, Ajuna.NetApi.Model.SpRuntime.EnumMultiAddress destination, BaseCom<Ajuna.NetApi.Model.Types.Primitive.U128> amount)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(owner.Encode());
            byteArray.AddRange(destination.Encode());
            byteArray.AddRange(amount.Encode());
            return new Method(7, "Assets", 22, "transfer_approved", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> touch
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Touch(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            return new Method(7, "Assets", 23, "touch", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> refund
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Refund(BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> id, Ajuna.NetApi.Model.Types.Primitive.Bool allow_burn)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(id.Encode());
            byteArray.AddRange(allow_burn.Encode());
            return new Method(7, "Assets", 24, "refund", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> Created
    /// Some asset class was created.
    /// </summary>
    public sealed class EventCreated : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> Issued
    /// Some assets were issued.
    /// </summary>
    public sealed class EventIssued : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Transferred
    /// Some assets were transferred.
    /// </summary>
    public sealed class EventTransferred : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> Burned
    /// Some assets were destroyed.
    /// </summary>
    public sealed class EventBurned : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> TeamChanged
    /// The management team changed.
    /// </summary>
    public sealed class EventTeamChanged : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> OwnerChanged
    /// The owner changed.
    /// </summary>
    public sealed class EventOwnerChanged : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> Frozen
    /// Some account `who` was frozen.
    /// </summary>
    public sealed class EventFrozen : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> Thawed
    /// Some account `who` was thawed.
    /// </summary>
    public sealed class EventThawed : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> AssetFrozen
    /// Some asset `asset_id` was frozen.
    /// </summary>
    public sealed class EventAssetFrozen : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> AssetThawed
    /// Some asset `asset_id` was thawed.
    /// </summary>
    public sealed class EventAssetThawed : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> Destroyed
    /// An asset class was destroyed.
    /// </summary>
    public sealed class EventDestroyed : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> ForceCreated
    /// Some asset class was force-created.
    /// </summary>
    public sealed class EventForceCreated : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> MetadataSet
    /// New metadata has been set for an asset.
    /// </summary>
    public sealed class EventMetadataSet : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>, BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>, Ajuna.NetApi.Model.Types.Primitive.U8, Ajuna.NetApi.Model.Types.Primitive.Bool>
    {
    }
    
    /// <summary>
    /// >> MetadataCleared
    /// Metadata has been cleared for an asset.
    /// </summary>
    public sealed class EventMetadataCleared : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32>
    {
    }
    
    /// <summary>
    /// >> ApprovedTransfer
    /// (Additional) funds have been approved for transfer to a destination account.
    /// </summary>
    public sealed class EventApprovedTransfer : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> ApprovalCancelled
    /// An approval for account `delegate` was cancelled by `owner`.
    /// </summary>
    public sealed class EventApprovalCancelled : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32>
    {
    }
    
    /// <summary>
    /// >> TransferredApproved
    /// An `amount` was transferred in its entirety from `owner` to `destination` by
    /// the approved `delegate`.
    /// </summary>
    public sealed class EventTransferredApproved : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>
    {
    }
    
    /// <summary>
    /// >> AssetStatusChanged
    /// An asset has had its attributes changed by the `Force` origin.
    /// </summary>
    public sealed class EventAssetStatusChanged : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32>
    {
    }
    
    public enum AssetsErrors
    {
        
        /// <summary>
        /// >> BalanceLow
        /// Account balance must be greater than or equal to the transfer amount.
        /// </summary>
        BalanceLow,
        
        /// <summary>
        /// >> NoAccount
        /// The account to alter does not exist.
        /// </summary>
        NoAccount,
        
        /// <summary>
        /// >> NoPermission
        /// The signing account has no permission to do the operation.
        /// </summary>
        NoPermission,
        
        /// <summary>
        /// >> Unknown
        /// The given asset ID is unknown.
        /// </summary>
        Unknown,
        
        /// <summary>
        /// >> Frozen
        /// The origin account is frozen.
        /// </summary>
        Frozen,
        
        /// <summary>
        /// >> InUse
        /// The asset ID is already taken.
        /// </summary>
        InUse,
        
        /// <summary>
        /// >> BadWitness
        /// Invalid witness data given.
        /// </summary>
        BadWitness,
        
        /// <summary>
        /// >> MinBalanceZero
        /// Minimum balance should be non-zero.
        /// </summary>
        MinBalanceZero,
        
        /// <summary>
        /// >> NoProvider
        /// Unable to increment the consumer reference counters on the account. Either no provider
        /// reference exists to allow a non-zero balance of a non-self-sufficient asset, or the
        /// maximum number of consumers has been reached.
        /// </summary>
        NoProvider,
        
        /// <summary>
        /// >> BadMetadata
        /// Invalid metadata given.
        /// </summary>
        BadMetadata,
        
        /// <summary>
        /// >> Unapproved
        /// No approval exists that would allow the transfer.
        /// </summary>
        Unapproved,
        
        /// <summary>
        /// >> WouldDie
        /// The source account would not survive the transfer and it needs to stay alive.
        /// </summary>
        WouldDie,
        
        /// <summary>
        /// >> AlreadyExists
        /// The asset-account already exists.
        /// </summary>
        AlreadyExists,
        
        /// <summary>
        /// >> NoDeposit
        /// The asset-account doesn't have an associated deposit.
        /// </summary>
        NoDeposit,
        
        /// <summary>
        /// >> WouldBurn
        /// The operation would result in funds being burned.
        /// </summary>
        WouldBurn,
    }
}
