//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.FrameSystem;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.AjunaRuntime
{
    
    
    public enum OriginCaller
    {
        
        system,
        
        Void,
    }
    
    /// <summary>
    /// >> 155 - Variant[ajuna_runtime.OriginCaller]
    /// </summary>
    public sealed class EnumOriginCaller : BaseEnumExt<OriginCaller, Ajuna.NetApi.Model.FrameSystem.EnumRawOrigin, Ajuna.NetApi.Model.Types.Base.BaseVoid>
    {
    }
}
